branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: molint
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
  drug-explore:
    branch: default
    repository: ebdjango
global:
  application_name: drugtool
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
