# Generated by Django 4.0.2 on 2022-08-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('ionizable', models.BooleanField(default=False)),
                ('polar', models.BooleanField(default=False)),
                ('parent_pKa', models.FloatField(max_length=4)),
                ('aromatic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Molecule_Name', models.CharField(max_length=50)),
                ('SMILES', models.CharField(max_length=200)),
                ('LiteraturePka', models.FloatField(max_length=5, null=True)),
                ('Difficulty', models.CharField(choices=[('easy', 'easy'), ('hard', 'hard')], default='easy', max_length=9)),
                ('Reference', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule_FG_pKa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(max_length=3)),
                ('pKa', models.FloatField(max_length=4)),
                ('pKa_type', models.CharField(choices=[('acidic', 'acidic'), ('basic', 'basic')], default='acidic', max_length=7)),
                ('FunctionalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.functionalgroup')),
                ('Molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.molecule')),
            ],
        ),
        migrations.CreateModel(
            name='AminoAcid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ionizable', models.BooleanField(default=False)),
                ('polar', models.BooleanField(default=False)),
                ('aromatic', models.BooleanField(default=False)),
                ('full_carbon_count', models.IntegerField(default=1, max_length=2)),
                ('branched', models.BooleanField(default=False)),
                ('essential', models.BooleanField(default=False)),
                ('singlet_code', models.CharField(default='', max_length=1)),
                ('triplet_code', models.CharField(default='', max_length=3)),
                ('charge', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='neutral', max_length=9)),
                ('sulfur', models.BooleanField(default=False)),
                ('volume', models.CharField(choices=[('Very Large', 'Very Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Very Small', 'Very Small')], default='Medium', max_length=11)),
                ('Molecule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.molecule')),
            ],
        ),
    ]
