# Generated by Django 4.0.2 on 2022-08-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapMode', models.BooleanField(default=False)),
                ('Time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='molecule',
            name='Ion_Type',
            field=models.CharField(choices=[('acid', 'acid'), ('base', 'base'), ('none', 'none')], default='none', max_length=9),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=40)),
                ('FGs_Solved', models.ManyToManyField(null=True, related_name='solvedfg_users', to='pharmaceutics.Molecule')),
                ('Maps_Solved', models.ManyToManyField(null=True, related_name='solvedmap_users', to='pharmaceutics.Molecule')),
                ('Pkas_Solved', models.ManyToManyField(null=True, related_name='solvedpka_users', to='pharmaceutics.Molecule')),
                ('Rotbs_Solved', models.ManyToManyField(null=True, related_name='solvedrotb_users', to='pharmaceutics.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.query')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz2Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=20)),
                ('Secs_Taken', models.IntegerField(max_length=5)),
                ('Answer1', models.CharField(max_length=6)),
                ('Answer2', models.CharField(max_length=6)),
                ('Answer3', models.CharField(max_length=6)),
                ('Answer4', models.CharField(max_length=6)),
                ('Answer5', models.CharField(max_length=6)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz1Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=20)),
                ('Secs_Taken', models.IntegerField(max_length=5)),
                ('Answer1', models.CharField(max_length=6, null=True)),
                ('Answer2', models.CharField(max_length=6, null=True)),
                ('Answer3', models.CharField(max_length=6, null=True)),
                ('Answer4', models.CharField(max_length=6, null=True)),
                ('Answer5', models.CharField(max_length=6, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.user')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='Molecules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.molecule'),
        ),
        migrations.AddField(
            model_name='query',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.user'),
        ),
    ]
