# Generated by Django 4.0.2 on 2022-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='litPka',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
