# Generated by Django 4.0.2 on 2022-08-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0002_query_molecule_ion_type_user_solvedquery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Difficulty', models.CharField(max_length=18)),
                ('Molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.molecule')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaceutics.user')),
            ],
        ),
    ]
