# Generated by Django 4.0.2 on 2022-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0003_alter_molecule_functionalgroups_alter_molecule_logp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='litPka',
            new_name='LiteraturePka',
        ),
        migrations.AddField(
            model_name='molecule',
            name='Difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard')], default='easy', max_length=9),
        ),
    ]
