# Generated by Django 4.0.2 on 2022-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0003_subjectivefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Qb2s_Solved',
            field=models.ManyToManyField(null=True, related_name='solvedqb2_users', to='pharmaceutics.Molecule'),
        ),
    ]
