# Generated by Django 4.0.2 on 2022-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0004_rename_litpka_molecule_literaturepka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='Reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
