# Generated by Django 4.0.2 on 2022-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0004_user_qb2s_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
