# Generated by Django 4.0.2 on 2022-08-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutics', '0006_remove_molecule_functionalgroups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='Name',
            new_name='Molecule_Name',
        ),
    ]
